server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trans?serverTimezone=Asia/Shanghai
    username: root
    password:
mybatis:
  type-aliases-package: io.matthew.common.entity
dubbo:
  application:
    id: provider
    name: provider
  registry:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://localhost:2181
  protocol:
    port: 20000
    name: dubbo
  monitor:
    protocol: registry
logging:
  level:
    com:
      marcus:
        dubbo: info