matt:
  data-sources:
    ds1:
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds1?characterEncoding=utf-8
    ds2:
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds2?characterEncoding=utf-8
    ds3:
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds3?characterEncoding=utf-8
  main: ds1

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: matt.mysql.entity


mapper:
  not-empty: false
  identity: MYSQL
  mappers: matt.mysql.tkMapper.GenericDao